### ISSUE TITLE
Implement OCR-based text extraction

### ISSUE THREAD

**Issue by paramsiddharth** [paramsiddharth/pdf2text#1]
# OCR-based Text Extraction
The `extract` function within `scanned.py` has yet to be implemented.
``` python
def extract(filename):
	... # TODO
```
## Details
- Since file validation checks have already been implemented in `main.py`, `filename` may be assumed to be a valid file. The directories `./out/` and `./out/imgs/` may also be assumed to be present.
- Desired `import` statements must be added.
- The function must convert the pages from the PDF file to images and store them temporarily in `out/imgs`.
- It must use Tesseract and Poppler to parse and extract text from each of the pages and store it in `out/output.txt`.
- It must delete the images after completing the operation.
- It must log of all the steps to the user in the console window.

## Reference
Refer to _[Tesseract PDF OCR](https://github.com/Manvendra2000/Reader) (A simple application that reads a PDF file and parses the text using the Tesseract OCR)_ for the implementation details. All the available modules are mentioned in `requirements.txt`.

**Comment by vanamayaswanth** [comment]
please assign me this work

**Comment by paramsiddharth** [comment]
@vanamayaswanth Assigning you this issue.

**Comment by tmedha** [comment]
Please assign this issue to me.

**Comment by paramsiddharth** [comment]
@tmedha Good luck!
