### ISSUE TITLE
Implement editable text extraction

### ISSUE THREAD

**Issue by paramsiddharth** [paramsiddharth/pdf2text#2]
# Editable Text Extraction
The `extract` function within `editable.py` has yet to be implemented.
``` python
def extract(filename):
	... # TODO
```
## Details
- Since file validation checks have already been implemented in `main.py`, `filename` may be assumed to be a valid file. The directories `./out/` and `./out/imgs/` may also be assumed to be present.
- Desired `import` statements must be added.
- The function must use PyPDF2 to parse and extract text from the PDF file and store it in `out/output.txt`.
- It must log of all the steps to the user in the console window.

## Reference
Refer to _[PDF File Reader](https://github.com/HarshMarolia/Pdf-File-Reader) (A simple Python application that reads out textual PDF files)_ for the implementation details. All the available modules are mentioned in `requirements.txt`.

**Comment by HarshMarolia** [comment]
I can implement it.

**Comment by paramsiddharth** [comment]
> I can implement it.

बहुत ख़ूब ! मैं यह मुद्दा अब तुम्हारे अधिकृत करता हूँ । 🥇

**Comment by vanamayaswanth** [comment]
please assign me this work

**Comment by paramsiddharth** [comment]
@vanamayaswanth Assigning you this issue.

**Comment by tmedha** [comment]
I would like to work on this. Please assign this work to me.

**Comment by paramsiddharth** [comment]
@tmedha Assigning you. Good luck!
